{% set name = "hydra-core" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/facebookresearch/hydra/archive/v{{ version }}.tar.gz
  sha256: 03840c5192d47c3b0a4cf57e1815f8626d36f2fed81efed59202f6bd93ac822c

build:
  noarch: python
  number: 1
  script:
    - {{ PYTHON }} setup.py antlr
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - antlr ==4.9
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - omegaconf ==2.1.*
    - antlr-python-runtime ==4.9

    # importlib_resources is only needed for Python 3.9, but can't
    # specify that with `noarch`
    - importlib_resources

test:
  imports:
    - hydra
  requires:
    - pytest
  source_files:
    - hydra
    - tests
    - examples
    - pytest.ini
    - ATTRIBUTION
  commands:
    - pytest -v tests/

about:
  home: https://hydra.cc/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A framework for elegantly configuring complex applications
  doc_url: https://hydra.cc/docs/intro/
  dev_url: https://github.com/facebookresearch/hydra

extra:
  recipe-maintainers:
    - mdraw
    - hadim
    - benjaminrwilson
